name: Terratest

on:
  push:
    # branches:
    # - feat/terratest-github-action

env:
  GCP_PROJECT_ID: padok-library-gcp-host
  GCP_SERVICE_ACCOUNT: "identity-terraform-gcp-network"

jobs:
  test:
    strategy:
      matrix:
        terratestTarget: [basic]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ GCP_PROJECT_ID.GCP }}/locations/global/workloadIdentityPools/identity-pool-padok-lab/providers/identity-provider-padok-lab"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Install dependencies
        working-directory: ./tests
        run: go mod tidy
      - name: Run terratest
        working-directory: tests
        run: go test -destroy
