name: Terratest

on:
  push:
    # branches:
    #   - main

env:
  TEST_WORKDIR: Monday

jobs:
  test:
    strategy:
      matrix:
        terratestTarget: [gke]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Check for terratestExample folder
      #   run: |
      #     if [ ! -d "terratestExample" ]; then
      #       echo "terratestExample folder not found, exiting..."
      #       exit 1
      #     fi
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        working-directory: ./tests
        run: go mod download github.com/Azure/azure-sdk-for-go
      - name: Run terratest
        working-directory: tests
        run: go test --args ../examples/${{matrix.terratestTarget}}
