name: Terratest

on:
  pull_request:
    branches:
      - main

env:
  GCP_PROJECT_ID: terratest-dev
  GCP_PROJECT_NUMBER: "704822998943"
  GCP_SERVICE_ACCOUNT: "gh-terratest-dev"

jobs:
  test:
    strategy:
      matrix:
        terratestTarget: [basic]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-identity/providers/github-oidc"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Install dependencies
        working-directory: ./tests
        run: go mod tidy
      - name: Run terratest
        working-directory: tests
        run: go test -destroy
